export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const ADD_RESTAURANT = "ADD_RESTAURANT";
export const ADD_RESTAURANT_TYPE = "ADD_RESTAURANT_TYPE";
export const FETCH_RESTAURANT_TYPES = "FETCH_RESTAURANT_TYPES";
export const FETCH_RESTAURANTS = "FETCH_RESTAURANTS";
export const EDIT_RESTAURANT = "EDIT_RESTAURANT";
export const EDIT_RESTAURANT_TYPE = "EDIT_RESTAURANT_TYPE";
export const ADD_FOOD_TYPE = "ADD_FOOD_TYPE";
export const FETCH_FOOD_TYPE = "FETCH_FOOD_TYPE";
export const EDIT_FOOD_TYPE = "EDIT_FOOD_TYPE";
export const DELETE_RESTAURANT_TYPE = "DELETE_RESTAURANT_TYPE";
export const DELETE_FOOD_TYPE = "DELETE_FOOD_TYPE";
export const ADD_FOOD_DETAILS = "ADD_FOOD_DETAILS";
export const ADD_MENU_NAME = "ADD_MENU_NAME";
export const FETCH_FOOD = "FETCH_FOOD";
export const FETCH_MENU_NAMES = "FETCH_MENU_NAMES";
export const ADD_GROUP_MENU = "ADD_GROUP_MENU";
export const FETCH_GROUP_MENUS = "FETCH_GROUP_MENUS";
export const FETCH_ORDER_DATA = "FETCH_ORDER_DATA";
